# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 's_s_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("#headerContainer {\n"
"  background-color: rgb(227,228,231);\n"
"}\n"
"\n"
"#headerNavigationBtnsContainer {\n"
"  background-color: rgb(227,228,231);\n"
"  border: none; \n"
"}\n"
"\n"
"#headerNavigationBtnsContainer QPushButton {\n"
"  background-color: rgb(227,228,231);\n"
"  border: none; \n"
"}\n"
"\n"
"#headerNavigationBtnsContainer QPushButton:hover {\n"
"  background-color: rgb(215,219,225); \n"
"}\n"
"\n"
"#headerNavigationBtnsContainer #closeBtn:hover {\n"
"  background-color: rgb(251,104,95); \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.headerContainer = QtWidgets.QWidget(self.centralwidget)
        self.headerContainer.setMinimumSize(QtCore.QSize(0, 30))
        self.headerContainer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.headerNavigationBtnsContainer = QtWidgets.QFrame(self.headerContainer)
        self.headerNavigationBtnsContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerNavigationBtnsContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerNavigationBtnsContainer.setObjectName("headerNavigationBtnsContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerNavigationBtnsContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.foldBtn = QtWidgets.QPushButton(self.headerNavigationBtnsContainer)
        self.foldBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.foldBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.foldBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.foldBtn.setIcon(icon)
        self.foldBtn.setObjectName("foldBtn")
        self.horizontalLayout_2.addWidget(self.foldBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.headerNavigationBtnsContainer)
        self.restoreBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.restoreBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.restoreBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon1)
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_2.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(self.headerNavigationBtnsContainer)
        self.closeBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.closeBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.horizontalLayout.addWidget(self.headerNavigationBtnsContainer, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.headerContainer, 0, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
